ECPMaster/ViewModels/DeploymentViewModel.cs
using System.Collections.Generic;
using ECPMaster.Entities;

namespace ECPMaster.ViewModels
{
    public class DeploymentViewModel
    {
        // create form
        public int NodeId { get; set; }
        public string ArtifactName { get; set; }
        public string SystemName { get; set; }
        public int SystemPort { get; set; }
        public string SubDomain { get; set; }
        public string DbBackupFileName { get; set; }
        public string DbName { get; set; }
        public int MySqlPort { get; set; }
        public string MySqlUser { get; set; }
        public string MySqlPassword { get; set; }
        
        // view data
        public List<ECPArtifact> Artifacts { get; set; }
        public List<ECPNode> Nodes { get; set; }
    }
}

ECPMaster/Controllers/DeploymentController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using ECPMaster.AsyncDataServices;
using ECPMaster.DbContext;
using ECPMaster.Entities;
using ECPMaster.Utils;
using ECPMaster.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace ECPMaster.Controllers
{
    public class DeploymentController : Controller
    {
        private readonly ECPDbContext _dbContext;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IServiceScopeFactory _serviceScopeFactory;

        public DeploymentController(ECPDbContext dbContext, IWebHostEnvironment hostEnvironment, IServiceScopeFactory serviceScopeFactory)
        {
            _dbContext = dbContext;
            _hostEnvironment = hostEnvironment;
            _serviceScopeFactory = serviceScopeFactory;
        }

        public async Task<IActionResult> DeploymentPipeline()
        {
            return View(new DeploymentViewModel()
            {
                Artifacts = await _dbContext.EcpArtifacts.ToListAsync(),
                Nodes = await NetworkUtils.UpdateNodesStatus(await _dbContext.EcpNodes.ToListAsync()),
                MySqlPort = 3306,
                MySqlUser = "root",
                SystemPort = 18001
            });
        }

        [HttpPost]
        public async Task<IActionResult> DeploymentPipeline(DeploymentViewModel model)
        {
            await using var transaction = await _dbContext.Database.BeginTransactionAsync();

            try
            {
                var artifact =
                    await _dbContext.EcpArtifacts.FirstOrDefaultAsync(a => a.Name.Equals(model.ArtifactName));

                var dbConfig = new ECPDbConfig()
                {
                    User = model.MySqlUser,
                    Password = model.MySqlPassword,
                    DbBackupFileName = model.DbBackupFileName,
                    Port = model.MySqlPort
                };

                await _dbContext.EcpDbConfigs.AddAsync(dbConfig);
                await _dbContext.SaveChangesAsync();

                var deployment = new ECPDeployment()
                {
                    Name = model.SystemName,
                    Port = model.SystemPort,
                    SubDomain = model.SubDomain,
                    Type = DeploymentType.Contained,
                    Status = DeploymentStatus.New,
                    NodeId = model.NodeId,
                    DbConfigId = dbConfig.Id,
                    ArtifactId = artifact.Id
                };
                await _dbContext.EcpDeployments.AddAsync(deployment);

                await _dbContext.SaveChangesAsync();

                await transaction.CommitAsync();
                
                var jobExecutor = new JobExecutor(_serviceScopeFactory);
                jobExecutor.ExecuteDeployment(await _dbContext
                    .EcpDeployments
                    .Include(d => d.Node)
                    .Include(d => d.Artifact)
                    .Include(d => d.DbConfig)
                    .FirstOrDefaultAsync(d => d.Id == deployment.Id));
                
                return RedirectToAction("ExecuteDeployment", new {deploymentId = deployment.Id});
            }
            catch (Exception)
            {
                await transaction.RollbackAsync();
            }

            return RedirectToAction("DeploymentPipeline");
        }

        public IActionResult ExecuteDeployment()
        {
            return View();
        }

        public async Task<IActionResult> ManageDeployments()
        {
            return View(await _dbContext.EcpDeployments
                .Include(d => d.Artifact)
                .Include(d => d.Node)
                .Include(d => d.DbConfig).ToListAsync());
        }
    }
}

ECPMaster/Views/Deployment/DeploymentPipeline.cshtml
@{
    ViewData["Title"] = "Deployment Pipeline";
    Layout = "_Layout";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/deployment-pipeline/deployment-pipeline.css"/>
    <link rel="stylesheet" href="~/css/my-dropdown.css/my-dropdown.css"/>
}

@using ECPMaster.Entities
@model ECPMaster.ViewModels.DeploymentViewModel

<div class="container">
<section>
    <div class="page-main-header">Deployment pipeline</div>
    <div class="page-sub-header">
        Build and deploy a system from current artifacts
    </div>
</section>
<section class="mt-2 main-page-content">
<div class="col-sm-10">
<form method="post">
<div class="d-flex justify-content-end">
    <button class="my-btn mr-2">Cancel</button>
    <button class="my-btn-danger" type="submit">Execute deployment</button>
</div>
<!-- deployment overview -->
<div class="my-card mt-3">
    <div class="my-card-header">Deployment overview</div>
    <div class="my-card-body">
        <div
            class="d-flex justify-content-center"
            style="font-weight: 600; font-size: 12px">
            <div class="d-flex flex-column align-items-end">
                <div>Deployment Server</div>
                <div>IPv4</div>
                <div>Port</div>
                <div>Artifact name</div>
                <div>System name</div>
                <div>Expose port rule</div>
                <div>Subdomain</div>
            </div>
            <div class="vertical-ruler"></div>
            <div
                class="d-flex flex-column align-items-start"
                style="font-weight: 500">
                <div>aws-88-server</div>
                <div>88.123.23.4</div>
                <div>8100</div>
                <div>lankem_uat</div>
                <div>lankem_test_v2</div>
                <div>0.0.0.0:8100</div>
                <div>lankem.evisionmicro.com</div>
            </div>
        </div>
    </div>
</div>
<!-- deployment overview end -->
<!-- server selection -->
<div class="my-card mt-5">
    <div class="my-card-header">Select an environment</div>
    <div class="my-card-body">
        <small style="color: #5d5f5f; font-weight: 600">
            Choose a deployment server
        </small
        >
        <input type="hidden" id="serverIdentifierInput" asp-for="NodeId">
        <div class="d-flex flex-wrap">
            @if (Model.Nodes != null && Model.Nodes.Any())
            {
                @foreach (var node in Model.Nodes)
                {
                    <!-- server item -->
                    <div class="server-container" id="servercontainer-@node.Id" onclick="fillHiddenInput('@node.Id')">
                        <div
                            class="server-container-left d-flex flex-column align-items-center justify-content-between mr-1">
                            <div>
                                <div style="font-size: 14px; font-weight: 900">
                                    @node.NodeIdentifier
                                </div>
                                <div
                                    style="
                            font-size: 12px;
                            font-weight: 500;
                            color: #232f3e;
                          ">
                                    IPv4: @node.IPv4
                                </div>
                            </div>
                        </div>
                        <div
                            class="server-container-right d-flex justify-content-center align-items-center ml-3">
                            @if (node.NodeState.Equals(AgentState.Available))
                            {
                                <div
                                    class="d-flex justify-content-center"
                                    style=" color: #266f16; font-size: 12px; font-weight: 900;">
                                    <i class="far fa-check-circle mr-1"></i>@node.NodeState
                                </div>
                            }
                            else
                            {
                                <div
                                    class="d-flex justify-content-center"
                                    style=" color: #CA2E2E; font-size: 12px; font-weight: 900;">
                                    <i class="far fa-check-circle mr-1"></i>@node.NodeState
                                </div>
                            }
                        </div>
                    </div>
                    <!-- server item end -->
                }
            }
        </div>
    </div>
</div>
<!-- server selection end -->

<!-- .Net core setup -->
<div class="my-card mt-5">
    <div class="my-card-header">Configure deployment system</div>
    <div class="my-card-body">
        <div class="col-sm-8">
            <div class="my-input-label mb-1">System name</div>
            <input
                class="form-control"
                type="text"
                asp-for="SystemName"
                placeholder="e.g. lankem_uat_system"/>
            <div class="my-input-footer-label mb-2 mt-1">
                *Unique identifier for the Deployment
            </div>

            <div class="my-input-label mb-1">Select artifact</div>
            <!-- Your custom dropdown container -->
            <div class="custom-dropdown d-flex">
                <input
                    class="dropdown-btn form-control"
                    asp-for="ArtifactName"
                    placeholder="Select an option"/>
                <ul class="dropdown-content">
                    <input
                        type="text"
                        class="search-input form-control"
                        placeholder="Search..."/>
                    <!-- options -->
                    @foreach (var artifacts in Model.Artifacts)
                    {
                        <li value="@artifacts.Name">
                            <div class="d-flex flex-column">
                                <div style="font-weight: 600; font-size: 12px">
                                    @artifacts.Name
                                </div>
                                <div style="font-size: 10px">
                                    ID: @artifacts.Id
                                </div>
                                <div style="font-size: 10px">
                                    Tags: @artifacts.Tag
                                </div>
                                <div style="font-size: 10px">
                                    Description: @artifacts.Url
                                </div>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- .net core setup end -->
<!-- environment variables setup -->
<div class="my-card mt-5">
    <div class="my-card-header">Configure variables</div>
    <div class="my-card-body">
        <div class="col-sm-8">
            <div class="my-input-label mb-1">Expose Port rule</div>
            <input
                class="form-control"
                type="text"
                asp-for="SystemPort"
                placeholder="e.g. 0.0.0.0:8100"/>
            <div class="my-input-footer-label mb-2 mt-1">
                *Unique identifier for the system
            </div>

            <div class="my-input-label mb-1">MySQL Port</div>
            <input
                class="form-control"
                type="text"
                asp-for="MySqlPort"
                placeholder="e.g. 0.0.0.0:8100"/>
            <div class="my-input-footer-label mb-2 mt-1">
                *Unique port for the mysql instance
            </div>

            <div class="my-input-label mb-1">MySQL User</div>
            <input
                class="form-control"
                type="text"
                asp-for="MySqlUser"
                placeholder="e.g. root"/>
            <div class="my-input-footer-label mb-2 mt-1">
                *Username of the mysql database
            </div>

            <div class="my-input-label mb-1">MySQL Password</div>
            <input
                class="form-control"
                type="password"
                asp-for="MySqlPassword"
                placeholder="e.g. xxxx"/>
            <div class="my-input-footer-label mb-2 mt-1">
                *Password of the mysql database
            </div>

            <div class="my-input-label mb-1">DB Name</div>
            <input
                class="form-control"
                type="text"
                asp-for="DbName"
                placeholder="e.g. golden_copy.sql"/>
            <div class="my-input-footer-label mb-2 mt-1">
                *Name for the db
            </div>

            <div class="my-input-label mb-1">DB Backup File name</div>
            <input
                class="form-control"
                type="text"
                asp-for="DbBackupFileName"
                placeholder="e.g. golden_copy.sql"/>
            <div class="my-input-footer-label mb-2 mt-1">
                *SQL file name for the db backup
            </div>

            <div class="my-input-label mb-1">
                Exposing subdomain (Optional)
            </div>
            <input
                class="form-control"
                asp-for="SubDomain"
                type="text"
                placeholder="e.g. subname.evisionmicro.com"/>
            <div class="my-input-footer-label mb-2 mt-1">
                *This will add a cloudflare DNS record
            </div>
        </div>
    </div>
</div>
<!-- environment variables setup end -->
</form>
</div>
</section>
</div>

@section Scripts
{
    <script src="~/js/my-dropdown.js"></script>
    <script>
        var previousClickedContainer = null;
        function fillHiddenInput(identifier) {
            // Retrieve the hidden input element
            var hiddenInput = document.getElementById('serverIdentifierInput');
            var serverContainer = document.getElementById('servercontainer-' + identifier);
             if (previousClickedContainer !== null) {
                    previousClickedContainer.classList.remove('clicked');
                }
            // Set the value of the hidden input to the server identifier
            hiddenInput.value = identifier;
            serverContainer.classList.toggle('clicked');
             previousClickedContainer = serverContainer;
        }
    </script>
}

ECPMaster/Views/Deployment/ExecuteDeployment.cshtml
@{
    ViewData["Title"] = "Execute Deployment";
    Layout = "_Layout";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/deployment-pipeline/deploying.css"/>
}

@model ECPMaster.ViewModels.ExecutionViewModel

<div class="container">
    <section>
        <div class="page-main-header">@ViewData["Title"]</div>
        <div class="page-sub-header">
            Build and deploy a system from current artifacts
        </div>
    </section>
    <section class="mt-2 main-page-content">
        <div class="col-sm-12">
            <div class="my-card status-container mt-4">
                <div class="my-card-header">Execution in progress</div>
                <div class="my-card-body p-0">
                    <div class="left-section">
                        <div class="summary-block">
                            <!-- task item -->
                            <div class="task-item">
                                <div class="task-info d-flex align-items-center">
                                    <ion-icon name="checkmark-circle-sharp" class="mx-4 my-3"></ion-icon>
                                    <div class="d-flex flex-column align-items-start">
                                        <div style="font-size: 14px; font-weight: 600">
                                            Deployment Server Available
                                        </div>
                                        <div style="font-size: 10px">1 successful check</div>
                                    </div>
                                </div>
                                <div class="subtask-list">
                                    <div class="subtask">
                                        <ion-icon
                                            name="checkmark-outline"
                                            class="mx-4">
                                        </ion-icon>
                                        <div>make a status check to server</div>
                                    </div>
                                </div>
                            </div>
                            <!-- task item end -->
                            <!-- task item -->
                            <div class="task-item">
                                <div class="task-info d-flex align-items-center">
                                    <ion-icon name="checkmark-circle-sharp" class="mx-4 my-3"></ion-icon>
                                    <div class="d-flex flex-column align-items-start">
                                        <div style="font-size: 14px; font-weight: 600">
                                            Connection established
                                        </div>
                                        <div style="font-size: 10px">2 successful check</div>
                                    </div>
                                </div>
                                <div class="subtask-list">
                                    <div class="subtask">
                                        <ion-icon
                                            name="checkmark-outline"
                                            class="mx-4">
                                        </ion-icon>
                                        <div>
                                            make a web socket / UDP connection with server
                                        </div>
                                    </div>
                                    <div class="subtask">
                                        <ion-icon
                                            name="checkmark-outline"
                                            class="mx-4">
                                        </ion-icon>
                                        <div>server accepted the connection</div>
                                    </div>
                                </div>
                            </div>
                            <!-- task item end -->
                            <!-- task item -->
                            <div class="task-item">
                                <div class="task-info d-flex align-items-center">
                                    <ion-icon name="checkmark-circle-sharp" class="mx-4 my-3"></ion-icon>
                                    <div class="d-flex flex-column align-items-start">
                                        <div style="font-size: 14px; font-weight: 600">
                                            Build the docker-compose.yaml file
                                        </div>
                                        <div style="font-size: 10px">1 successful check</div>
                                    </div>
                                </div>
                                <div class="subtask-list">
                                    <div class="subtask">
                                        <ion-icon
                                            name="checkmark-outline"
                                            class="mx-4">
                                        </ion-icon>
                                        <div>
                                            created a docker compose file with variables
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- task item end -->
                            <!-- task item -->
                            <div class="task-item">
                                <div class="task-info d-flex align-items-center">
                                    <ion-icon name="checkmark-circle-sharp" class="mx-4 my-3"></ion-icon>
                                    <div class="d-flex flex-column align-items-start">
                                        <div style="font-size: 14px; font-weight: 600">
                                            Execute the docker compose file
                                        </div>
                                        <div style="font-size: 10px">2 successful check</div>
                                    </div>
                                </div>
                                <div class="subtask-list">
                                    <div class="subtask">
                                        <ion-icon
                                            name="checkmark-outline"
                                            class="mx-4">
                                        </ion-icon>
                                        <div>
                                            created docker volumes / copy docker-compose.yaml
                                        </div>
                                    </div>
                                    <div class="subtask">
                                        <ion-icon
                                            name="checkmark-outline"
                                            class="mx-4">
                                        </ion-icon>
                                        <div>executed command --docker compose up</div>
                                    </div>
                                </div>
                            </div>
                            <!-- task item end -->
                            <!-- task item -->
                            <div class="task-item">
                                <div class="task-info d-flex align-items-center">
                                    <ion-icon name="checkmark-circle-sharp" class="mx-4 my-3"></ion-icon>
                                    <div class="d-flex flex-column align-items-start">
                                        <div style="font-size: 14px; font-weight: 600">
                                            docker compose status
                                        </div>
                                        <div style="font-size: 10px">1 successful check</div>
                                    </div>
                                </div>
                                <div class="subtask-list">
                                    <div class="subtask">
                                        <ion-icon
                                            name="checkmark-outline"
                                            class="mx-4">
                                        </ion-icon>
                                        <div>
                                            run docker compose logs and check if the system is
                                            live
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- task item end -->
                        </div>
                    </div>
                    <div class="right-section p-0">
                        <div class="my-card">
                            <div class="my-card-header"><img id="rotating-image" src="/assets/loader.gif" class="mr-2" alt="" style="height: 15px; width: 15px;">Virtual Terminal</div>
                            <div class="my-card-body">
                                <textarea
                        disabled
                        class="output"
                        id="terminal"
                      ></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@section Scripts
{
    @* <script *@
    @*     src="https://cdn.socket.io/4.6.0/socket.io.min.js" *@
    @*     integrity="sha384-c79GN5VsunZvi+Q/WObgk2in0CbZsHnjEqvFxC5DxHn9lTfNce2WW6h2pH6u/kF+" *@
    @*     crossorigin="anonymous"></script> *@
    <script>
         const term = document.getElementById("terminal");
          term.value = "";
    @*   *@
    @*      function removeBackspaces(input) { *@
    @*        const output = []; *@
    @*   *@
    @*        for (const char of input) { *@
    @*          if (char === "\b") { *@
    @*            output.pop(); // Remove the last character *@
    @*          } else { *@
    @*            output.push(char); *@
    @*          } *@
    @*        } *@
    @*   *@
    @*        return output.join(""); *@
    @*      } *@
    let urlParams = new URLSearchParams(window.location.search);
    
  function writeln(log) {
    term.value += log.line + "\n";
    term.scrollTop = term.scrollHeight;
    lastId = log.id;
  }
  
  let lastId = 0;
  
  setInterval(() => {
      fetch('/api/DeploymentApi/GetLogs?deploymentId=' + urlParams.get('deploymentId') + '&offset=' + lastId)
        .then(response => response.json())
        .then(data => {
          data.forEach((log) => writeln(log))
        })
        .catch(error => {
          console.error('Error fetching JSON:', error);
        });
  },3000)
    @*   *@
    @*      const randomUUID = generateUUID(); *@
    @*          // Connect to the socket.io server *@
    @*          const socket = io("http://68.183.190.210:12000", { *@
    @*            query: { *@
    @*              sessionID: randomUUID, *@
    @*              customData: "additionalInfo", *@
    @*            }, *@
    @*          }); // Replace with your server URL *@
    @*       *@
    @*          // Listen for events from the server *@
    @*          socket.on("connect", () => { *@
    @*            console.log("Connected to server"); *@
    @*            writeln("Connected to server") *@
    @*          }); *@
    @*       *@
    @*          socket.on("privateStream", (data) => { *@
    @*            console.log("Received message:", data); *@
    @*            try { *@
    @*              writeln(JSON.parse(data).content) *@
    @*            } catch (e) { *@
    @*                writeln(data) *@
    @*                } *@
    @*          }); *@
    @*       *@
    @*          function generateUUID() { *@
    @*            let uuid = "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace( *@
    @*              /[xy]/g, *@
    @*              function (c) { *@
    @*                const r = (Math.random() * 16) | 0; *@
    @*                const v = c === "x" ? r : (r & 0x3) | 0x8; *@
    @*                return v.toString(16); *@
    @*              } *@
    @*            ); *@
    @*       *@
    @*            return uuid; *@
    @*          } *@
    </script>
}

ECPMaster/Views/Deployment/ManageDeployments.cshtml
@{
    ViewData["Title"] = "Manage Deployments";
}

@model IEnumerable<ECPMaster.Entities.ECPDeployment>;

@section Styles
{
    <link rel="stylesheet" href="~/css/IAMrole/iam-role.css"/>
}

<div class="container">
    <section>
        <div class="page-main-header">@ViewData["Title"]</div>
        <div class="page-sub-header">
            View all deployment history
        </div>
    </section>
    <section class="mt-2 main-page-content">
        <div class="col-sm-12">
            <div class="d-flex justify-content-end">
                <a class="my-btn" asp-action="DeploymentPipeline" asp-controller="Deployment">Create Deployment</a>
            </div>
            <div class="my-card mt-3">
                <div class="my-card-header">ECP Deployments</div>
                <div class="my-card-body">
                    <div class="d-flex flex-wrap">
                        @foreach (var deployment in Model)
                        {
                            <!-- role item -->
                            <div class="role-container">
                                <div
                                    class="role-container-left d-flex flex-column justify-content-between mr-3">
                                    <div>
                                        <div style="font-size: 14px; font-weight: 900;" class="d-flex align-items-center">
                                            <div
                                                class="info-pair-subtitle status-badge-@deployment.Id"
                                                style="color: #266f16; font-size: 22px! important;">
                                                <i class="far fa-check-circle mr-1"></i>
                                            </div>
                                            <div>Deployment: @deployment.Name</div>
                                        </div>
                                        <div style="font-size: 12px; font-weight: 500; color: #232F3E;">Deployment Name: @deployment.Id</div>
                                        <div style="font-size: 12px; font-weight: 500; color: #232F3E;">Artifact: @deployment.Artifact.Name:@deployment.Artifact.Tag</div>
                                        <div style="font-size: 12px; font-weight: 500; color: #232F3E;">Node: @deployment.Node.NodeIdentifier</div>
                                        <div style="font-size: 12px; font-weight: 500; color: #232F3E;">Deployment Type: @deployment.Type</div>
                                    </div>
                                    <div class="mt-3" style="font-size: 10px; color: #232F3E; font-style: italic;">Click here to view more</div>
                                </div>
                                <div
                                    class="role-container-right d-flex justify-content-end align-items-center">
                                    <a class="my-btn mr-2" asp-action="EditRole" asp-controller="Administration" asp-route-id="@deployment.Id">edit</a>
                                    <a class="my-btn-danger" asp-action="DeleteRole" asp-controller="Administration" asp-route-id="@deployment.Id"
                                       onclick="return confirm('Are you sure to destroy this deployment : @deployment.Name')">
                                        destroy
                                    </a>
                                </div>
                            </div>
                            <!-- role item end -->
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>